# Generated by Django 4.0.1 on 2022-01-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
