# Generated by Django 4.0.1 on 2022-01-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['insert_timestamp']},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='timestamp',
            new_name='insert_timestamp',
        ),
    ]
